@WinterRose_ClientHub_HostAddress = http://localhost:5089

GET {{WinterRose_ClientHub_HostAddress}}/apps/summaries
Accept: application/json

###
GET {{WinterRose_ClientHub_HostAddress}}/apps
Accept: application/winterforge

###