using Eto;
using Eto.Drawing;
using Eto.Forms;

namespace WinterRose.Nexus.Interface;

/// <summary>
/// Styling, generated by AI with color guidance by me. aint no way im writing this styling base myself lmao
/// </summary>
public static class ThemeManager
{
    public static class NexusPalette
    {
        public static readonly Color BG = Color.FromArgb(14, 6, 18);
        public static readonly Color BG_ELEVATED = Color.FromArgb(23, 12, 29);
        public static readonly Color BG_CARD = Color.FromArgb(28, 15, 36);

        public static readonly Color BORDER = Color.FromArgb(45, 22, 64);
        public static readonly Color BORDER_SOFT = Color.FromArgb(36, 20, 51);

        public static readonly Color ACCENT = Color.FromArgb(252, 173, 255);
        public static readonly Color ACCENT_DIM = Color.FromArgb(201, 142, 209);

        public static readonly Color TEXT = Color.FromArgb(255, 255, 255);
        public static readonly Color TEXT_MUTED = Color.FromArgb(184, 168, 192);

        public static readonly Color DANGER = Color.FromArgb(255, 90, 106);
        public static readonly Color DANGER_SOFT = Color.FromArgb(40, 255, 90, 106);

        public static readonly Color DEBUG = Color.FromArgb(110, 110, 120);
        public static readonly Color SUCCESS = Color.FromArgb(120, 255, 120);
        public static readonly Color WARNING = Color.FromArgb(255, 225, 80);
        public static readonly Color ERROR = Color.FromArgb(255, 120, 120);
    }

    public static void ApplyNexusTheme()
    {
        ApplyGtkCss();
        ApplyEtoStyles();
    }
    
    public static void ApplyGtkCss()
    {
        Gtk.CssProvider cssProvider = new();

        cssProvider.LoadFromData("""
                                 /* =========================================================
                                    GLOBAL RESET (GTK ONLY)
                                    ========================================================= */

                                 *,
                                 *:hover,
                                 *:active,
                                 *:checked,
                                 *:selected,
                                 *:backdrop,
                                 *:disabled {
                                     background-image: none;
                                     box-shadow: none;
                                     text-shadow: none;
                                     border-image: none;
                                     -gtk-icon-shadow: none;
                                     outline-color: alpha(#fcadff, 0);
                                 }

                                 /* =========================================================
                                    GLOBAL BASE COLORS
                                    ========================================================= */

                                 progressbar trough {
                                     background-color: #170c1d;
                                     border-radius: 6px;
                                     min-height: 8px;
                                 }
                                 
                                 progressbar progress {
                                     background-color: #fcadff;
                                     border-radius: 6px;
                                     min-height: 8px;
                                 }
                                 
                                 progressbar progress {
                                     transition: width 150ms ease;
                                 }
                                 
                                 * {
                                     border-color: #2d1640;
                                     caret-color: #fcadff;
                                     font-family: "Cascadia Code";
                                    font-size: 12px;
                                 }

                                 window {
                                     background-color: #0e0612;
                                 }
                                 
                                 .background {
                                     background-color: #0e0612;
                                 }

                                 box,
                                 grid,
                                 paned,
                                 box, 
                                 grid, 
                                 paned,
                                 flowbox,
                                 alignment  {
                                     background-color: #0e0612;
                                     font-family: "Cascadia Code";
                                 }
                                 
                                 checkbutton,
                                 checkbutton label,
                                 checkbutton:checked label,
                                 checkbutton:hover label,
                                 checkbutton:active label,
                                 checkbutton:disabled label {
                                     color: #ffffff;
                                 }

                                 frame,
                                 viewport,
                                 scrolledwindow {
                                     background-color: #170c1d;
                                     border: 1px solid #2d1640;
                                     border-radius: 10px;
                                 }

                                 /* =========================================================
                                    LIST INTERACTION (GTK ONLY)
                                    ========================================================= */

                                 list row:hover {
                                     background-color: alpha(#fcadff, 0.08);
                                 }

                                 list row:selected {
                                     background-color: #241433;
                                     border-left: 3px solid #fcadff;
                                 }

                                 /* =========================================================
                                    INPUT FOCUS (GTK ONLY)
                                    ========================================================= */

                                 entry:focus,
                                 searchentry:focus,
                                 textview:focus {
                                     border-color: #fcadff;
                                 }

                                 /* =========================================================
                                    SELECTION
                                    ========================================================= */

                                 selection,
                                 *:selected {
                                     background-color: #fcadff;
                                     color: #0e0612;
                                 }

                                 /* =========================================================
                                    BUTTON RENDERING (GTK ONLY BASE)
                                    ========================================================= */

                                 button > *,
                                 button box,
                                 button image {
                                     background-color: transparent;
                                     background-image: none;
                                 }

                                 button {
                                     background-color: #1c0f24;
                                     border: 1px solid #2d1640;
                                     color: #ffffff;
                                 }

                                 button:hover {
                                     background-color: #241433;
                                 }

                                 button:active {
                                     background-color: #170c1d;
                                 }
                                 
                                 button:disabled {
                                    background-color: #3F2933;
                                 }

                                 /* =========================================================
                                    SCROLL + HEADER
                                    ========================================================= */

                                 scrollbar slider {
                                     background-color: #2d1640;
                                 }
                                 
                                 scrollbar,
                                 scrollbar trough {
                                     background-color: transparent;
                                 }

                                 headerbar {
                                     background-color: #0e0612;
                                     border-bottom: 1px solid #2d1640;
                                 }
                                 
                                 
                                 menu {
                                     background-color: #0e0612;
                                     border: 1px solid #2d1640;
                                     padding: 6px;
                                     border-radius: 8px;
                                 }
                                 
                                 menuitem {
                                     background-color: transparent;
                                     color: #ffffff;
                                     padding: 6px 10px;
                                     border-radius: 6px;
                                 }
                                 
                                 menuitem:hover {
                                     background-color: #241433;
                                 }
                                 
                                 menuitem:active {
                                     background-color: #170c1d;
                                 }
                                 
                                 menuitem:disabled {
                                     color: alpha(#ffffff, 0.4);
                                 }
                                 
                                 
                                 /* =========================================================
                                    POPUPS / DROPDOWNS (GTK4 / COMBOBOX SUPPORT)
                                    ========================================================= */
                                 
                                 popover,
                                 popover.background {
                                     background-color: #0e0612;
                                     border: 1px solid #2d1640;
                                     border-radius: 10px;
                                 }
                                 
                                 popover contents {
                                     background-color: transparent;
                                 }
                                 
                                 
                                 /* =========================================================
                                    COMBOBOX (GTK ONLY)
                                    ========================================================= */
                                 
                                 combobox {
                                     background-color: #1c0f24;
                                     border: 1px solid #2d1640;
                                     border-radius: 6px;
                                 }
                                 
                                 combobox button {
                                     background-color: transparent;
                                     border: none;
                                 }
                                 
                                 combobox button:hover {
                                     background-color: #241433;
                                 }
                                 
                                 combobox arrow {
                                     color: #fcadff;
                                 }
                                 
                                 combobox entry {
                                     background-color: #1c0f24;
                                     color: #ffffff;
                                     border: none;
                                 }
                                 
                                 
                                 /* dropdown list inside combobox */
                                 combobox menu {
                                     background-color: #0e0612;
                                     border: 1px solid #2d1640;
                                 }
                                 
                                 /* =========================================================
                                    TAB CONTROL / NOTEBOOK (GTK ONLY)
                                    ========================================================= */
                                 
                                 notebook {
                                     background-color: #0e0612;
                                     border: 1px solid #2d1640;
                                     border-radius: 10px;
                                 }
                                 
                                 /* tab header strip */
                                 notebook header {
                                     background-color: #0e0612;
                                     border-bottom: 1px solid #2d1640;
                                 }
                                 
                                 /* individual tabs */
                                 notebook tab {
                                     background-color: #1c0f24;
                                     border: 1px solid #2d1640;
                                     padding: 6px 12px;
                                     margin: 2px;
                                     border-radius: 6px;
                                     color: #ffffff;
                                 }
                                 
                                 notebook tab * {
                                    background-color: transparent;   
                                 }
                                 
                                 /* hover state */
                                 notebook tab:hover {
                                     background-color: #241433;
                                 }
                                 
                                 /* active/selected tab */
                                 notebook tab:checked {
                                     background-color: #170c1d;
                                     border-bottom: 2px solid #fcadff;
                                     color: #fcadff;
                                 }
                                 
                                 /* tab label inside */
                                 notebook tab label {
                                     color: inherit;
                                 }
                                 
                                 /* page/content area */
                                 notebook stack,
                                 notebook > stack {
                                     background-color: #0e0612;
                                     padding: 10px;
                                 }
                                 
                                 /* optional: remove ugly focus outlines */
                                 notebook tab:focus {
                                     outline: none;
                                 }
                                 
                                 scale {
                                     min-width: 140px;
                                     min-height: 18px;
                                     padding: 4px;
                                 }
                                 
                                 scale trough {
                                     background-color: #170c1d;
                                     border-radius: 6px;
                                     min-height: 6px;
                                 }
                                 
                                 scale highlight {
                                     background-color: #fcadff;
                                     border-radius: 6px;
                                 }
                                 
                                 scale slider {
                                     background-color: #fcadff;
                                     min-width: 16px;
                                     min-height: 16px;
                                     border-radius: 50%;
                                     margin: -6px;
                                 }
                                 
                                 spinbutton {
                                     background-color: #1c0f24;
                                     border: 1px solid #2d1640;
                                     border-radius: 6px;
                                     color: #ffffff;
                                     padding: 4px;
                                     min-width: 80px;
                                 }
                                 
                                 spinbutton entry {
                                     background-color: transparent;
                                     color: #ffffff;
                                     border: none;
                                 }
                                 
                                 spinbutton button {
                                     background-color: transparent;
                                     border: none;
                                     padding: 2px 6px;
                                 }
                                 
                                 spinbutton button:hover {
                                     background-color: #241433;
                                 }
                                 
                                 spinbutton button:active {
                                     background-color: #170c1d;
                                 }
                                 """);

        Gtk.StyleContext.AddProviderForScreen(
            Gdk.Screen.Default,
            cssProvider,
            uint.MaxValue
        );
    }
    
    public static void ApplyEtoStyles()
    {
        // =========================================================
        // WINDOW
        // =========================================================

        Style.Add<Window>("nexus-window", c => { c.BackgroundColor = NexusPalette.BG; });

        // =========================================================
        // CARDS
        // =========================================================

        Style.Add<Panel>("card", c => { c.BackgroundColor = NexusPalette.BG_CARD; });

        Style.Add<Panel>("card-elevated", c => { c.BackgroundColor = NexusPalette.BG_ELEVATED; });

        // =========================================================
        // LABELS
        // =========================================================

        Style.Add<Label>(null, c => { c.TextColor = NexusPalette.TEXT; });
        
        Style.Add<Label>("muted", c => { c.TextColor = NexusPalette.TEXT_MUTED; });
        Style.Add<Label>("accent", c => { c.TextColor = NexusPalette.ACCENT; });
        
        Style.Add<Label>("log-debug", c => c.TextColor = NexusPalette.DEBUG);
        Style.Add<Label>("log-info", c => c.TextColor = NexusPalette.TEXT);
        Style.Add<Label>("log-success", c => c.TextColor = NexusPalette.SUCCESS);
        Style.Add<Label>("log-warning", c => c.TextColor = NexusPalette.WARNING);
        Style.Add<Label>("log-error", c => c.TextColor = NexusPalette.ERROR);

        // =========================================================
        // BUTTONS
        // =========================================================

        Style.Add<Button>(null, c =>
        {
            c.BackgroundColor = NexusPalette.BG_CARD;
            c.TextColor = NexusPalette.TEXT;
        });

        Style.Add<Button>("primary", c =>
        {
            c.BackgroundColor = NexusPalette.ACCENT;
            c.TextColor = NexusPalette.BG;
        });

        Style.Add<Button>("destructive", c =>
        {
            c.BackgroundColor = NexusPalette.DANGER_SOFT;
            c.TextColor = NexusPalette.ERROR;
        });

        // =========================================================
        // INPUTS
        // =========================================================

        Style.Add<TextBox>(null, c =>
        {
            c.BackgroundColor = NexusPalette.BG_ELEVATED;
            c.TextColor = NexusPalette.TEXT;
        });

        Style.Add<TextArea>(null, c =>
        {
            c.BackgroundColor = NexusPalette.BG_ELEVATED;
            c.TextColor = NexusPalette.TEXT;
        });

        // =========================================================
        // LISTS
        // =========================================================

        Style.Add<ListBox>(null, c =>
        {
            c.BackgroundColor = NexusPalette.BG_ELEVATED;
            c.TextColor = NexusPalette.TEXT;
        });

        // =========================================================
        // SCROLLABLE
        // =========================================================

        Style.Add<Scrollable>(null, c => { c.BackgroundColor = NexusPalette.BG; });
    }
}